# Generated by Django 2.1.8 on 2019-07-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_order_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='googd_count',
            new_name='goods_count',
        ),
    ]
