# Generated by Django 2.1.8 on 2019-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_auto_20190729_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
